In [2]:
import pandas as pd

In [3]:
info={
    "name":["Razzaq","Hakim","Hilal"],
    "CGPA":[8,9,9.5]
}
df=pd.DataFrame(info)
print(df)

     name  CGPA
0  Razzaq   8.0
1   Hakim   9.0
2   Hilal   9.5

In [4]:
df

     name  CGPA
0  Razzaq   8.0
1   Hakim   9.0
2   Hilal   9.5

In [7]:
s=pd.Series([1,2,3,4])
print(s)
print(s[0])
print(s[1])

0    1
1    2
2    3
3    4
dtype: int64
1
2

In [10]:
s=pd.Series([23,24,25,26,"abc"],index=["Razzaq","Ahamad","Hakim","Alim",27])
print(s)
print(s.index)

Razzaq     23
Ahamad     24
Hakim      25
Alim       26
27        abc
dtype: object
Index(['Razzaq', 'Ahamad', 'Hakim', 'Alim', 27], dtype='object')

In [13]:
s1=pd.Series([1,2,3,4])
s2=pd.Series([20,21,22,23])
print(s1+s2)
print(s1**s2)
s1[0]=100
changed_s1=s1.drop(0)
print(s1)
print(changed_s1)

0    21
1    23
2    25
3    27
dtype: int64
0                 1
1           2097152
2       31381059609
3    70368744177664
dtype: int64
0    100
1      2
2      3
3      4
dtype: int64
1    2
2    3
3    4
dtype: int64

In [19]:
#dataframes using dictionary
info={
    "name":["Razzaq","Ahamad","Hakim"],
    "age":[22,23,24],
    "gpa":[8,9.2,9.5]
}
df=pd.DataFrame(info)
print(df)
print(type(df))
print(df.index)
print(df.columns)

     name  age  gpa
0  Razzaq   22  8.0
1  Ahamad   23  9.2
2   Hakim   24  9.5
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['name', 'age', 'gpa'], dtype='object')

In [21]:
#dataframe using list of list
df=pd.DataFrame([["Razzaq",22],["Hakim",23],["Alim",24]])
print(df)

        0   1
0  Razzaq  22
1   Hakim  23
2    Alim  24

In [23]:
import numpy as np
np_arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(np_arr,columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [24]:
#CSV Data
df=pd.read_csv("employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [25]:
df=pd.read_json("employee_data.json")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [42]:
#dataframe methods
#df.head()
#df.tail(2)
#df.sample()
#df.info()
#df.shape
df.describe()
df.columns
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [46]:
#AQI DataSet
df=pd.read_csv("globalAirQuality[1].csv")
df.describe()
df.head()
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [63]:
df
#selecting columns
df[["city","aqi"]]
#selecting rows
df.loc[1]
df.loc[0:2]  #inclusive
df.iloc[1]
df.iloc[0:2] #exclusive
df.loc[0:2,["city","aqi"]]
df.columns
df.loc[0:2,["city","aqi"]]
df.iloc[0:3,1:5]
df.at[0,"city"]
df.iat[0,2]

'New York'